In [ ]:
1 Write the Python code to implement a single neuron.
Ans: Neural networks are the core of deep learning, a field that has practical applications in many different areas. Today neural networks are used for image classification, speech recognition, object detection, etc. Now, Let’s try to understand the basic unit behind all these states of art techniques.
A single neuron transforms given input into some output. Depending on the given input and weights assigned to each input, decide whether the neuron fired or not. Let’s assume the neuron has 3 input connections and one output.
 

2 Write the Python code to implement ReLU.
Ans: 
Relu or Rectified Linear Activation Function is the most common choice of activation function in the world of deep learning. Relu provides state of the art results and is computationally very efficient at the same time.

3 Write the Python code for a dense layer in terms of matrix multiplication.
Ans:  m = size(X, 1);
2:  X = [ones(m,1),X]; 
3:  a1 = X;
4:  z2 = Theta1*a1';
5:  a2 = sigmoid(z2);
6:  a2 = [ones(1,m);a2];
7:  z3 = Theta2*a2;
8:  a3 = sigmoid(z3);
9:  yv=[1:4] == y;
10: J = (1/m) * (sum(-yv’ .* log(a3) — ((1 — yv’) .* log(1 — a3))));
11: J = sum(J);


4 Write the Python code for a dense layer in plain Python (that is, with list comprehensions and functionality built into Python).
Ans:  txns = [1.09, 23.56, 57.84, 4.56, 6.78]
>>> TAX_RATE = .08
>>> def get_price_with_tax(txn):
...     return txn * (1 + TAX_RATE)
>>> final_prices = map(get_price_with_tax, txns)
>>> list(final_prices)
[1.1772000000000002, 25.4448, 62.467200000000005, 4.9248, 7.322400000000001]


5 What is the “hidden size” of a layer?
Ans: 
Apart from the fact mentioned above, that the size of the layers represents the network complexity, there is also an aspect of representation quality.
In a few papers higher-dimensional representation were used to make the learning problem easier. Can provide you some references if you are interested.
For example, one can use Sparse Autoencoder with middle layer having more nodes than input later to achieve sparse representation: this representation would contain more numbers, but most of them would be zeros. It is computationally efficient and great for interpretability.


6 What does the t method do in PyTorch?
Ans: The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.


7 Why is matrix multiplication written in plain Python very slow?
Ans: 

Python is not a complied programing language it is interpreted. Libraries like numpy and .tensorflow are write in C or C++.

8 In matmul, why is ac==br?
Ans: 
Let ar,ac be the number of rows and columns in A. Similarly, let br, bc be the number of rows and columns in B. Then in order to carry out matrix multiplication it is necessary that ac == br. Why? Well, as you saw in excel we multiplied rows and columns element wise and then added the intermediate products to get the final result. If there is mismatch in dimensions, and one vector is longer than the other, we can no longer carry out element wise multiplication!
The dimensions of the resulting matrix will always be ar,bc. That is the number of rows comes from A and the number of columns comes from B.

9 In Jupyter Notebook, how do you measure the time taken for a single cell to execute?
Ans: 

The only way I found to overcome this problem is by executing the last statement with print.

 cell magic starts with %% and line magic starts with %.

%%time
clf = tree.DecisionTreeRegressor().fit(X_train, y_train)
res = clf.predict(X_test)
print(res)

10 What is elementwise arithmetic?
Ans: 
Know how to create arrays : array, arange, ones, zeros.

Know the shape of the array with array.shape, then use slicing to obtain different views of the array: array[::2], etc. Adjust the shape of the array using reshape or flatten it with ravel.

Obtain a subset of the elements of an array and/or modify their values with masks

>>>
a[a < 0] = 0
Know miscellaneous operations on arrays, such as finding the mean or max (array.max(), array.mean()). No need to retain everything, but have the reflex to search in the documentation (online docs, help(), lookfor())!!

For advanced use: master the indexing with arrays of integers, as well as broadcasting. Know more NumPy functions to handle various array operations.


11 Write the PyTorch code to test whether every element of a is greater than the corresponding element of b.
Ans: import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
lin = nn.Linear(5, 3)  # maps from R^5 to R^3, parameters A, b
# data is 2x5.  A maps from 5 to 3... can we map "data" under A?
data = torch.randn(2, 5)
print(lin(data))  # yes


12 What is a rank-0 tensor? How do you convert it to a plain Python data type?
Ans: All elements are of a single known data type.

When writing a TensorFlow program, the main object that is manipulated and passed around is the tf.Tensor.

A tf.Tensor has the following properties:

a single data type (float32, int32, or string, for example)
a shape
TensorFlow supports eager execution and graph execution. In eager execution, operations are evaluated immediately. In graph execution, a computational graph is constructed for later evaluation.

TensorFlow defaults to eager execution. In the example below, the matrix multiplication results are calculated immediately.
 How does elementwise arithmetic help us speed up matmul?
14 What are the broadcasting rules?
Ans: 
Recall that for arrays of the same size, binary operations are performed on an element-by-element basis:

import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b
array([5, 6, 7])
Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example, we can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

a + 5
array([5, 6, 7])
We can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

We can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:

M = np.ones((3, 3))
M
array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])
M + a
array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])
Here the one-dimensional array a is stretched, or broadcast across the second dimension in order to match the shape of M.

While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays.


15 What is expand_as? Show an example of how it can be used to match the results of broadcasting.
Ans: 
Information function. We have a need for information to satisfy curiosity, reduce uncertainty, and better understand how we fit into the world. The amount and availability of information is now overwhelming compared to forty years ago when a few television networks, local radio stations, and newspapers competed to keep us informed. The media saturation has led to increased competition to provide information, which creates the potential for news media outlets, for example, to report information prematurely, inaccurately, or partially.
Interpretation function. Media outlets interpret messages in more or less explicit and ethical ways. Newspaper editorials have long been explicit interpretations of current events, and now cable television and radio personalities offer social, cultural, and political commentary that is full of subjective interpretations. Although some of them operate in ethical gray areas because they use formats that make them seem like traditional news programs, most are open about their motives.
Instructive function. Some media outlets exist to cultivate knowledge by teaching instead of just relaying information. Major news networks like CNN and BBC primarily serve the information function, while cable news networks like Fox News and MSNBC serve a mixture of informational and interpretation functions. The in-depth coverage on National Public Radio and the Public Broadcasting Service, and the more dramatized but still educational content of the History Channel, the National Geographic Channel, and the Discovery Channel, serve more instructive functions.
Bonding function. Media outlets can bring people closer together, which serves the bonding function. For example, people who share common values and interests can gather on online forums, and masses of people can be brought together while watching coverage of a tragic event like 9/11 or a deadly tornado outbreak.
Diversion function. We all use the media to escape our day-to-day lives, to distract us from our upcoming exam, or to help us relax. When we are being distracted, amused, or relaxed, the media is performing the diversion function.
